name: Network Discovery - lint
on:
  push:
    branches:
      - "!release"
    paths:
      - "network-discovery/**"
      - "!network-discovery/docker/**"
  pull_request:
    paths:
      - "network-discovery/**"
      - "!network-discovery/docker/**"

permissions:
  contents: read

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          check-latest: true
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.62
          working-directory: network-discovery
          args: --config ../.github/golangci.yaml
          skip-pkg-cache: true
          skip-build-cache: true