name: Network Discovery - test
on:
  push:
    branches:
      - "!release"
    paths:
      - "network-discovery/**"
      - "!network-discovery/docker/**"
  pull_request:
    paths:
      - "network-discovery/**"
      - "!network-discovery/docker/**"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write

jobs:
  go-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: network-discovery
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          check-latest: true
      - name: Run go build
        run: go build ./...
      - name: Install additional dependencies
        run: |
          go install github.com/mfridman/tparse@v0.14.0
          sudo apt-get -y install nmap
      - name: Run go test
        id: go-test
        run: |
          make test-coverage
          echo 'coverage-report<<EOF' >> $GITHUB_OUTPUT
          cat .coverage/test-report.md >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
          echo "coverage-total=$(cat .coverage/coverage.txt)" >> $GITHUB_OUTPUT
      - name: Output Result
        if: always()
        run: cat .coverage/test-report.md
      - name: Find comment
        uses: peter-evans/find-comment@v3
        id: existing-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Go test coverage
      - name: Post comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.existing-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Go test coverage
            ${{ steps.go-test.outputs.coverage-report }}
            Total coverage: ${{ steps.go-test.outputs.coverage-total }}%
          edit-mode: replace