name: SNMP Discovery - lint
on:
  push:
    branches:
      - "!release"
    paths:
      - "snmp-discovery/**"
      - "!snmp-discovery/docker/**"
  pull_request:
    paths:
      - "snmp-discovery/**"
      - "!snmp-discovery/docker/**"

permissions:
  contents: read

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'snmp-discovery/go.mod'
      - name: Lint
        uses: golangci/golangci-lint-action@db582008a42febd596419635a5abc9d9815daa9c # v9.2.1
        with:
          version: v2.11.3
          working-directory: snmp-discovery
          args: --config ../.github/golangci.yaml
